services:
  meta-gen-postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: meta-gen
      POSTGRES_DB: meta-gen
      POSTGRES_USER: meta-gen
    ports:
      - 15439:5432
    volumes:
      - ./volume/metagen:/var/lib/postgresql/data
    container_name: meta-gen-postgres
    networks:
      - meta-network
  meta-gen-redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - 16379:6379
    networks:
      - meta-network

networks:
  meta-network:
    driver: bridge
